import { Link } from 'react-router-dom';

import { LegalPage } from './LegalPage.jsx';

export function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="21 May 2026" version="v1">
      <p>
        Raktify is operated by <strong>Choudhari EduHealth India Foundation</strong>, a
        registered non-profit (NGO-DARPAN MH/2025/0643345, 80G eligible) headquartered in
        Amravati, Maharashtra, India. This policy explains what personal data we collect
        when you use Raktify, how we use it, who we share it with, and the rights you
        have under India&rsquo;s <strong>Digital Personal Data Protection Act 2023 (DPDP Act)</strong>.
      </p>
      <p>
        Raktify is free to use. We do not sell personal data, ever. We do not run
        advertising. The platform is funded by CSR partners and individual donations to
        the Foundation.
      </p>

      <h2>1. Who this policy applies to</h2>
      <p>
        This policy applies to everyone who uses Raktify in any capacity:
      </p>
      <ul>
        <li><strong>Donors</strong> who register on the platform to give blood.</li>
        <li><strong>Coordinators</strong> — NGO volunteers responsible for a district.</li>
        <li><strong>Hospitals</strong> and <strong>blood banks</strong> that onboard institutionally.</li>
        <li><strong>NGO admins</strong> and <strong>super admins</strong> who operate the platform.</li>
        <li><strong>Camp organisers</strong> who host public blood-donation camps.</li>
        <li><strong>Recipients of WhatsApp notifications</strong> from the platform.</li>
      </ul>

      <h2>2. What personal data we collect</h2>
      <h3>2.1 Information you provide directly</h3>
      <ul>
        <li>Full name, date of birth, gender, preferred language.</li>
        <li>Mobile number (used for OTP authentication; encrypted at rest).</li>
        <li>Email address (institutional users only).</li>
        <li>Address (village, taluka, district, pincode); GPS coordinates are not collected.</li>
        <li>Self-reported blood group (not used for matching — see § 5).</li>
        <li>Aadhaar last 4 digits or other government-ID last 4 digits for coordinator verification (full Aadhaar number is never collected).</li>
      </ul>

      <h3>2.2 Information generated by your interactions</h3>
      <ul>
        <li>Donation history (dates, components, volumes, blood bank). Donations are recorded by the blood bank at which you donate.</li>
        <li>Lab-verified blood group (written only by the blood bank&rsquo;s verified staff).</li>
        <li>Transfusion-transmissible-infection (TTI) screening verdict per donation. Field-level test results never leave the blood bank&rsquo;s screening interface.</li>
        <li>Eligibility status, deferral state and next-eligible date.</li>
        <li>Consent records — when you gave or withdrew consent, and for what purposes.</li>
        <li>Camp registration / RSVP history.</li>
        <li>Notification delivery logs (sent, delivered, read; for service reliability).</li>
      </ul>

      <h3>2.3 Information collected automatically</h3>
      <ul>
        <li>IP address and approximate location of every authenticated request, for audit and abuse prevention.</li>
        <li>Browser type and PWA version, for compatibility.</li>
        <li>A locally-stored authentication token (JWT) in your browser&rsquo;s localStorage so you stay signed in. Cleared on logout.</li>
        <li>An IndexedDB outbox that queues your availability toggles offline; replays automatically when you reconnect.</li>
      </ul>

      <h2>3. Why we collect each category</h2>
      <p>Every column below is the strict legal basis under the DPDP Act for each data category:</p>
      <table>
        <thead>
          <tr><th>Data</th><th>Purpose</th><th>Lawful basis (DPDP § 7)</th></tr>
        </thead>
        <tbody>
          <tr><td>Mobile + name + DOB</td><td>Authenticate the donor; match them to emergency requests</td><td>Consent + legitimate use (medical emergency)</td></tr>
          <tr><td>Verified blood group</td><td>Determine compatibility with patient&rsquo;s requested group</td><td>Consent (granted during donor registration)</td></tr>
          <tr><td>Donation history + TTI verdict</td><td>Enforce deferral periods; safety of recipients</td><td>Legitimate use (statutory: Drugs &amp; Cosmetics Act, 1940 / blood-bank regulations)</td></tr>
          <tr><td>IP &amp; device info</td><td>Audit log, abuse prevention</td><td>Legitimate use (security)</td></tr>
          <tr><td>Camp RSVPs</td><td>Roster the donor for the camp organiser; remind them of the date</td><td>Consent (you RSVP'd)</td></tr>
        </tbody>
      </table>

      <h2>4. How we protect your data</h2>
      <p>
        Raktify is engineered as a life-critical healthcare system. Patient safety and donor
        privacy are enforced at the database layer, not just in application code:
      </p>
      <ul>
        <li><strong>Row-Level Security (RLS)</strong> on every table. A coordinator from one district cannot read another district&rsquo;s data even with valid credentials.</li>
        <li><strong>Two-key hybrid encryption.</strong> Free-text PII (name, address) is encrypted with one AES-256-GCM key; TTI screening data with a separate key. A compromised application server cannot decrypt TTI data without separately compromising the screening key.</li>
        <li><strong>Hash-chained audit log.</strong> Every state change in the system is appended to an immutable, SHA-256-chained audit log. Backdating or tampering breaks the chain and is detected automatically.</li>
        <li><strong>Mobile masking.</strong> Your phone number is encrypted at rest and never returned to hospital users in API responses. Hospitals see <code>+91XXXXX1234</code> at most.</li>
        <li><strong>TLS everywhere.</strong> All data in transit between your device, Raktify, and any third party is encrypted via TLS 1.2 or higher.</li>
        <li><strong>Data residency.</strong> All Raktify data is hosted in Microsoft Azure&rsquo;s Central India region (Pune).</li>
      </ul>

      <h2>5. The "self-reported blood group never used in matching" invariant</h2>
      <p>
        Donors enter their own blood group during registration so the platform can show it to
        them with an "Unverified" badge. <strong>This self-reported value is never queried by
        the matching engine.</strong> Only the lab-verified blood group — writable solely by
        an authenticated blood-bank user — is used for matching donors to emergency requests.
        This is a hard-coded rule in the matching algorithm and is enforced at the database
        layer.
      </p>

      <h2>6. Who we share your data with</h2>
      <p>
        We share <em>only</em> what is necessary, only with the parties listed below, and only
        for the purposes listed below:
      </p>
      <ul>
        <li><strong>Coordinators in your district</strong> — see your name and blood group when activating donors for an emergency request, never your mobile number directly. All communication is mediated by the platform.</li>
        <li><strong>The blood bank where you donate</strong> — has full access to your donation record at that bank, your verified blood group, your eligibility state, and your TTI screening results.</li>
        <li><strong>The hospital you respond to (if any)</strong> — sees only that someone with the right blood group is willing to donate; never your name or contact.</li>
        <li><strong>Camp organisers (when you RSVP)</strong> — see your name and blood group; mobile number is never shared.</li>
        <li><strong>Choudhari EduHealth India Foundation operations team</strong> — for audit, abuse investigation, and grievance redressal.</li>
      </ul>

      <h3>6.1 Third-party processors</h3>
      <p>
        We use the following sub-processors. All are bound by data-processing agreements and,
        where applicable, India-resident or covered by standard contractual clauses:
      </p>
      <ul>
        <li><strong>Microsoft Azure (Central India)</strong> — cloud hosting, database, secrets management.</li>
        <li><strong>Meta Platforms Ireland</strong> — WhatsApp message delivery via Cloud API. Meta receives your mobile number and the template message content; Meta does not see your other personal data.</li>
        <li><strong>Leegality (Aadhaar eSign provider)</strong> — used only when an institutional signatory eSigns the Raktify Memorandum of Understanding. Donors do not interact with this provider.</li>
      </ul>
      <p>
        We do not share your data with advertising networks, data brokers, or analytics
        providers that track individual users across the web.
      </p>

      <h2>7. Your rights under DPDP Act 2023</h2>
      <p>You have the following rights, and we will honour each within 30 days of a valid request:</p>
      <ul>
        <li><strong>Right to access</strong> — a copy of all personal data we hold about you, in a machine-readable format.</li>
        <li><strong>Right to correction</strong> — fix any incorrect or outdated information.</li>
        <li><strong>Right to erasure</strong> — see our <Link to="/data-deletion">Data deletion</Link> page for the precise process and what we cannot delete (audit records mandated by law are anonymised but retained).</li>
        <li><strong>Right to withdraw consent</strong> — at any time, from the donor dashboard or by emailing us. Withdrawal does not affect the lawfulness of prior processing.</li>
        <li><strong>Right to nominate</strong> — designate someone to exercise your rights on your behalf, including in the event of death or incapacity.</li>
        <li><strong>Right to grievance redressal</strong> — see § 11 for our Grievance Officer contact.</li>
      </ul>

      <h2>8. Data retention</h2>
      <ul>
        <li><strong>Active donor profile</strong> — retained while your account is active and for 12 months after your last activity, after which we proactively contact you to reconfirm consent.</li>
        <li><strong>Donation history at a blood bank</strong> — retained by the blood bank per Drugs &amp; Cosmetics Act requirements (typically 5 years). On erasure, we anonymise the link between you and the records — the records themselves cannot be destroyed by law.</li>
        <li><strong>TTI screening results</strong> — retained for 7 years per public-health-traceability requirements (lookback registry).</li>
        <li><strong>Audit log entries</strong> — retained permanently (hash-chained, cannot be deleted); on erasure, PII fields are nulled out while the hash chain is preserved.</li>
        <li><strong>Notification logs</strong> — retained 12 months, then aggregated to anonymous statistics.</li>
      </ul>

      <h2>9. Children&rsquo;s data</h2>
      <p>
        You must be 18 years or older to donate blood and to register as a donor on Raktify. We
        do not knowingly collect data from children under 18.
      </p>
      <p>
        We do hold data about minors enrolled in our <strong>thalassemia patient registry</strong>.
        That data is added by a treating hospital or an authorised guardian; it is gated by
        Row-Level Security so only the treating hospital, the patient&rsquo;s assigned
        coordinator, and NGO admins can see it. The guardian&rsquo;s mobile number is the only
        contact channel and is held under the same encryption and access controls as a
        donor&rsquo;s.
      </p>

      <h2>10. International data transfers</h2>
      <p>
        Raktify data is stored in Microsoft Azure&rsquo;s Central India (Pune) region. Some
        third-party processors (notably Meta for WhatsApp delivery) operate outside India. The
        Government of India has designated specific countries as restricted; we will update
        this policy if any of our processors are added to that list.
      </p>

      <h2>11. Grievance redressal</h2>
      <p>
        If you have a concern about your data, a complaint about how we&rsquo;ve handled it, or
        you wish to exercise any of the rights in § 7:
      </p>
      <p>
        <strong>Grievance Officer:</strong> Gaurav R. Choudhari<br />
        <strong>Email:</strong> <a href="mailto:contact@choudhari.ngo">contact@choudhari.ngo</a><br />
        <strong>Phone:</strong> <a href="tel:+919850541412">+91 98505 41412</a><br />
        <strong>Address:</strong> Choudhari EduHealth India Foundation, 54, 2nd Lane, Rathi Nagar, VMV Road, Amravati, Maharashtra 444603
      </p>
      <p>
        We will acknowledge your grievance within 72 hours and resolve it within 30 days. If
        you are not satisfied with our response, you may approach the Data Protection Board of
        India under DPDP Act 2023.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        When we change this policy, we will update the "Last updated" date at the top of this
        page. Material changes will be announced via in-app notification and (for institutional
        users) by email. Continued use of Raktify after a change constitutes acceptance.
      </p>
    </LegalPage>
  );
}
